name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        rust: [stable, 1.88.0]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run tests
        run: cargo test --all-targets

  docs:
    runs-on: windows-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-docs

      - name: Generate documentation
        run: cargo doc --workspace --no-deps

  rustfmt:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Format Rust code
        run: cargo fmt --all -- --check

  clippy:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Lint Rust code
        run: cargo clippy --all-targets -- -D warnings
